version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000 --reload

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ordis_user
      POSTGRES_PASSWORD: ordis_pass
      POSTGRES_DB: ordis_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
