"""add-qty-to-line-item

Revision ID: 0786f2bce2fe
Revises: 5e41b6a454bf
Create Date: 2025-08-31 16:03:54.183534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0786f2bce2fe'
down_revision = '5e41b6a454bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_column('qty')

    # ### end Alembic commands ###
