"""empty message

Revision ID: 191223252b6f
Revises: 0786f2bce2fe
Create Date: 2025-08-31 18:03:08.434656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191223252b6f'
down_revision = '0786f2bce2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_tech_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_orders_tech_id'))
        batch_op.create_index(batch_op.f('ix_orders_service_tech_id'), ['service_tech_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_orders_tech_id_employees'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_service_tech_id_employees'), 'employees', ['service_tech_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tech_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_orders_service_tech_id_employees'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_tech_id_employees'), 'employees', ['tech_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_orders_service_tech_id'))
        batch_op.create_index(batch_op.f('ix_orders_tech_id'), ['tech_id'], unique=False)
        batch_op.drop_column('service_tech_id')

    # ### end Alembic commands ###
