"""add-token-blacklist

Revision ID: 23d0bc1842bd
Revises: 7bb5746e6753
Create Date: 2025-09-14 13:47:26.666370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d0bc1842bd'
down_revision = '7bb5746e6753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blacklist')),
    sa.UniqueConstraint('jti', name=op.f('uq_token_blacklist_jti'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
