"""adjust-models-for-user-auth

Revision ID: 7bb5746e6753
Revises: 191223252b6f
Create Date: 2025-09-07 13:54:56.898580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb5746e6753'
down_revision = '191223252b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Enum('CUSTOMER', 'EMPLOYEE', 'ADMIN', name='user_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_customers_email'), type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_customers_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_employees_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_employees_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_customers_user_id_users'), type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_customers_email'), ['email'])
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
